//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedShape.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gym
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gym()
        {
            this.GymAgreements = new HashSet<GymAgreement>();
            this.GymPayments = new HashSet<GymPayment>();
            this.GymServices = new HashSet<GymService>();
            this.GymUsers = new HashSet<GymUser>();
            this.GymMembers = new HashSet<GymMember>();
            this.UserStatements = new HashSet<UserStatement>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
        public string Name { get; set; }
        public string TradingName { get; set; }
        public string RegNo { get; set; }
        public string Email { get; set; }
        public string Cell { get; set; }
        public string Fax { get; set; }
        public string Reference { get; set; }
        public string POPEmail { get; set; }
        public string CompanyEmail { get; set; }
        public string ContactPerson { get; set; }
        public string ContactTel { get; set; }
        public string ContactEmail { get; set; }
        public string ContactCell { get; set; }
        public int Status { get; set; }
        public System.DateTime StatusDate { get; set; }
        public string VATNo { get; set; }
        public string Website { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApproverComments { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GymAgreement> GymAgreements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GymPayment> GymPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GymService> GymServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GymUser> GymUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GymMember> GymMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserStatement> UserStatements { get; set; }
    }
}
