//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedShape.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymTime
    {
        public int Id { get; set; }
        public int GymServiceId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<bool> OpenOnMonday { get; set; }
        public Nullable<System.TimeSpan> MondayStart { get; set; }
        public Nullable<System.TimeSpan> MondayClose { get; set; }
        public Nullable<bool> OpenOnTuesday { get; set; }
        public Nullable<System.TimeSpan> TuesdayStart { get; set; }
        public Nullable<System.TimeSpan> TuesdayClose { get; set; }
        public Nullable<bool> OpenOnWednesday { get; set; }
        public Nullable<System.TimeSpan> WednesdayStart { get; set; }
        public Nullable<System.TimeSpan> WednesdayClose { get; set; }
        public Nullable<bool> OpenOnThursday { get; set; }
        public Nullable<System.TimeSpan> ThursdayStart { get; set; }
        public Nullable<System.TimeSpan> ThursdayClose { get; set; }
        public Nullable<bool> OpenOnFriday { get; set; }
        public Nullable<System.TimeSpan> FridayStart { get; set; }
        public Nullable<System.TimeSpan> FridayClose { get; set; }
        public Nullable<bool> OpenOnSaturday { get; set; }
        public Nullable<System.TimeSpan> SaturdayStart { get; set; }
        public Nullable<System.TimeSpan> SaturdayClose { get; set; }
        public Nullable<bool> OpenOnSunday { get; set; }
        public Nullable<System.TimeSpan> SundayStart { get; set; }
        public Nullable<System.TimeSpan> SundayClose { get; set; }
        public Nullable<bool> OpenOnPublicHoliday { get; set; }
        public Nullable<System.TimeSpan> PublicHolidayStart { get; set; }
        public Nullable<System.TimeSpan> PublicHolidayClose { get; set; }
    
        public virtual GymService GymService { get; set; }
    }
}
